### ISSUE TITLE
TimeoutError: waiting for target failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by Ruiy8640** [fleece-the-flock/cuttlefish#1]
你好,
獲取墨斗魚數據了，但是一定超時就結束了，這裏要做什麽調整嗎？
麻煩看下，謝謝
![image](https://user-images.githubusercontent.com/34324446/211704761-86899c46-2d03-437e-a365-1d558b2a8806.png)

**Comment by liuliangsir** [comment]
可以贴一下你的环境配置吗？比如 Node.js 版本、使用的包管理工具及版本等信息
