### ISSUE TITLE
请问访问getquerypacklist接口的cookie中没有AB-SR应该去哪找呢？

### ISSUE THREAD

**Issue by ZHOUXIAONAN** [fleece-the-flock/cuttlefish#7]
请问访问getquerypacklist接口的cookie中没有AB-SR应该去哪找呢？

**Comment by liuliangsir** [comment]
其实你可以看下不用这个 cookie 是否能访问到？你再认真找一下，我自己这里可以看到。

![image](https://user-images.githubusercontent.com/8049878/218616697-ba3c1e8e-c730-4727-a572-e239a6d5beea.png)

**Comment by ZHOUXIAONAN** [comment]
感谢回复！我又仔细检查了一遍，还是没有ab_sr字段。是否是需要现在文库中进行什么操作呢？

**Comment by ZHOUXIAONAN** [comment]
感谢回复！我又仔细检查了一遍，还是没有ab_sr字段。是否是需要现在文库中进行什么操作呢？

**Comment by ZHOUXIAONAN** [comment]
-  感谢回复！我又仔细检查了一遍，我的 [百度文库->创作者中心->任务中心->创作活动] 页面中的cookie还是没有ab_sr字段。是否是需要先在百度文库中进行什么权限操作呢？

- 另外，我尝试了一下在getQuestion文件的cookie中不添加ab_sr字段，报错`接口请求情况：not login error`。可能是需要这个字段

**Comment by liuliangsir** [comment]
推荐换个浏览器或者浏览器开无痕模式

**Comment by ZHOUXIAONAN** [comment]
非常感谢，可以运行了^ ^
